#!/bin/bash
echo -e "User\tJobID\tNode\tJobName\tPartition\tState\tTime\tReqMem\tReqCPUS\tGPU\n" > ~/queueinfo.txt
sacct  --state R,PD --format=User,JobID,nodelist,Jobname%30,partition,state,time,ReqMem,ReqCPUS,ReqTRES%-42  | grep "vss2134"  - | tr -s " " | sed "s/^ //g" - |sed "s/None assigned/None/g" | tr  " " "\t" | awk '{$NF=gensub(/.*gpu=([0-9]+).*/, "gpu=\\1", 1, $NF)}1' >> ~/queueinfo.txt
cat ~/queueinfo.txt | column -t
